apiVersion: v1
kind: Service
metadata:
  name: nlp-ml-webapp-service
  namespace: default
spec:
  selector:
      app: nlp-ml-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001

