apiVersion: v1
kind: Service
metadata:
  name: alp-ml-webapp-extservice
  namespace: default
spec:
  selector:
      app: nlp-ai-webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30000

